[manager]
prepend_keymap = [
  { on = "z", run = "plugin zoxide" },
  { on = "Z", run = "plugin fzf" },
]

append_keymap = [
  { on = [ "g", "C" ], run = "cd C:", desc = "Go to C drive", for = "windows" },
  { on = [ "g", "D" ], run = "cd D:", desc = "Go to D drive", for = "windows" },
  { on = [ "g", "E" ], run = "cd E:", desc = "Go to E drive", for = "windows" },
]

