[manager]
show_hidden = true

[opener]
play = [
	{ run = 'flatpak run --command=mpv io.mpv.Mpv "$@"', orphan = true, for = "linux" },
	{ run = 'D:\ProgramFiles\mpv.net\mpvnet.exe %*', orphan = true, for = "windows" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
	{ run = 'start "%1"', orphan = true, desc = "Open", for = "windows" },
	{ run = 'open "%1"', orphan = true, desc = "Open", for = "macos" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
]
