[manager]
show_hidden = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "linux" },
	{ run = 'D:\ProgramFiles\mpv.net\mpvnet.exe %*', orphan = true, for = "windows" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
	{ run = 'start "" %*', orphan = true, desc = "Open", for = "windows" },
	{ run = 'open "$0"', orphan = true, desc = "Open", for = "macos" },
]

